image: Visual Studio 2022

environment:
  nodejs_version: "23"

branches:
  only:
    - master

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

build_script:
  - npm run build

test_script:
  - npm run lint && npm test
